//----------------------------------------------------------------------------------------
// patterns & practices - Smart Client Software Factory - Guidance Package
//
// This file was generated by this guidance package as part of the solution template
//
// The IWorkItemController is the interface that WorkItemControllers must implement. 
// It specifies a single method, Run.
// 
// For more information see: 
// ms-help://MS.VSCC.v80/MS.VSIPCC.v80/ms.scsf.2006jun/SCSF/html/03-210-Creating%20a%20Smart%20Client%20Solution.htm
//
// Latest version of this Guidance Package: http://go.microsoft.com/fwlink/?LinkId=62182
//----------------------------------------------------------------------------------------


namespace Taumis.Infrastructure.Interface
{
    /// <summary>
    /// Controller used by <see cref="ControlledWorkItem{TController}"/>.
    /// </summary>
    public interface IWorkItemController
    {
        /// <summary>
        /// Called when the controller is ready to run.
        /// </summary>
        void Run();
    }
}