//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taumis.Alpha.Infrastructure.Interface.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Taumis.Alpha.Infrastructure.Interface.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка чтения профайла для модуля {0}..
        /// </summary>
        internal static string EModuleProfile {
            get {
                return ResourceManager.GetString("EModuleProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сервис {0} не найден..
        /// </summary>
        internal static string EServiceNotFound {
            get {
                return ResourceManager.GetString("EServiceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новая карточка.
        /// </summary>
        internal static string GridStringId_CardViewNewCard {
            get {
                return ResourceManager.GetString("GridStringId.CardViewNewCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настроить.
        /// </summary>
        internal static string GridStringId_CardViewQuickCustomizationButton {
            get {
                return ResourceManager.GetString("GridStringId.CardViewQuickCustomizationButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фильтр.
        /// </summary>
        internal static string GridStringId_CardViewQuickCustomizationButtonFilter {
            get {
                return ResourceManager.GetString("GridStringId.CardViewQuickCustomizationButtonFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сортировать:.
        /// </summary>
        internal static string GridStringId_CardViewQuickCustomizationButtonSort {
            get {
                return ResourceManager.GetString("GridStringId.CardViewQuickCustomizationButtonSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Желаете изменить значение?.
        /// </summary>
        internal static string GridStringId_ColumnViewExceptionMessage {
            get {
                return ResourceManager.GetString("GridStringId.ColumnViewExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле.
        /// </summary>
        internal static string GridStringId_CustomFilterDialog2FieldCheck {
            get {
                return ResourceManager.GetString("GridStringId.CustomFilterDialog2FieldCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Отменить.
        /// </summary>
        internal static string GridStringId_CustomFilterDialogCancelButton {
            get {
                return ResourceManager.GetString("GridStringId.CustomFilterDialogCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отобразить строки где:.
        /// </summary>
        internal static string GridStringId_CustomFilterDialogCaption {
            get {
                return ResourceManager.GetString("GridStringId.CustomFilterDialogCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Очистить фильтр.
        /// </summary>
        internal static string GridStringId_CustomFilterDialogClearFilter {
            get {
                return ResourceManager.GetString("GridStringId.CustomFilterDialogClearFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пустые.
        /// </summary>
        internal static string GridStringId_CustomFilterDialogConditionBlanks {
            get {
                return ResourceManager.GetString("GridStringId.CustomFilterDialogConditionBlanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Равно.
        /// </summary>
        internal static string GridStringId_CustomFilterDialogConditionEQU {
            get {
                return ResourceManager.GetString("GridStringId.CustomFilterDialogConditionEQU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Больше.
        /// </summary>
        internal static string GridStringId_CustomFilterDialogConditionGT {
            get {
                return ResourceManager.GetString("GridStringId.CustomFilterDialogConditionGT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Больше или равно.
        /// </summary>
        internal static string GridStringId_CustomFilterDialogConditionGTE {
            get {
                return ResourceManager.GetString("GridStringId.CustomFilterDialogConditionGTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Содержится.
        /// </summary>
        internal static string GridStringId_CustomFilterDialogConditionLike {
            get {
                return ResourceManager.GetString("GridStringId.CustomFilterDialogConditionLike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Меньше.
        /// </summary>
        internal static string GridStringId_CustomFilterDialogConditionLT {
            get {
                return ResourceManager.GetString("GridStringId.CustomFilterDialogConditionLT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Меньше или равно.
        /// </summary>
        internal static string GridStringId_CustomFilterDialogConditionLTE {
            get {
                return ResourceManager.GetString("GridStringId.CustomFilterDialogConditionLTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не равно.
        /// </summary>
        internal static string GridStringId_CustomFilterDialogConditionNEQ {
            get {
                return ResourceManager.GetString("GridStringId.CustomFilterDialogConditionNEQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Непустые.
        /// </summary>
        internal static string GridStringId_CustomFilterDialogConditionNonBlanks {
            get {
                return ResourceManager.GetString("GridStringId.CustomFilterDialogConditionNonBlanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не содержится.
        /// </summary>
        internal static string GridStringId_CustomFilterDialogConditionNotLike {
            get {
                return ResourceManager.GetString("GridStringId.CustomFilterDialogConditionNotLike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расширенный фильтр.
        /// </summary>
        internal static string GridStringId_CustomFilterDialogFormCaption {
            get {
                return ResourceManager.GetString("GridStringId.CustomFilterDialogFormCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;OK.
        /// </summary>
        internal static string GridStringId_CustomFilterDialogOkButton {
            get {
                return ResourceManager.GetString("GridStringId.CustomFilterDialogOkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;И.
        /// </summary>
        internal static string GridStringId_CustomFilterDialogRadioAnd {
            get {
                return ResourceManager.GetString("GridStringId.CustomFilterDialogRadioAnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;ИЛИ.
        /// </summary>
        internal static string GridStringId_CustomFilterDialogRadioOr {
            get {
                return ResourceManager.GetString("GridStringId.CustomFilterDialogRadioOr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Диапазоны.
        /// </summary>
        internal static string GridStringId_CustomizationBands {
            get {
                return ResourceManager.GetString("GridStringId.CustomizationBands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки.
        /// </summary>
        internal static string GridStringId_CustomizationCaption {
            get {
                return ResourceManager.GetString("GridStringId.CustomizationCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Колонки.
        /// </summary>
        internal static string GridStringId_CustomizationColumns {
            get {
                return ResourceManager.GetString("GridStringId.CustomizationColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для настройки вида поместите сюда объединенный заголовок.
        /// </summary>
        internal static string GridStringId_CustomizationFormBandHint {
            get {
                return ResourceManager.GetString("GridStringId.CustomizationFormBandHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для настройки вида поместите сюда заголовок колонки.
        /// </summary>
        internal static string GridStringId_CustomizationFormColumnHint {
            get {
                return ResourceManager.GetString("GridStringId.CustomizationFormColumnHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл {0} не найден.
        /// </summary>
        internal static string GridStringId_FileIsNotFoundError {
            get {
                return ResourceManager.GetString("GridStringId.FileIsNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Применить.
        /// </summary>
        internal static string GridStringId_FilterBuilderApplyButton {
            get {
                return ResourceManager.GetString("GridStringId.FilterBuilderApplyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Отменить.
        /// </summary>
        internal static string GridStringId_FilterBuilderCancelButton {
            get {
                return ResourceManager.GetString("GridStringId.FilterBuilderCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактор фильтра.
        /// </summary>
        internal static string GridStringId_FilterBuilderCaption {
            get {
                return ResourceManager.GetString("GridStringId.FilterBuilderCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;OK.
        /// </summary>
        internal static string GridStringId_FilterBuilderOkButton {
            get {
                return ResourceManager.GetString("GridStringId.FilterBuilderOkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактировать фильтр.
        /// </summary>
        internal static string GridStringId_FilterPanelCustomizeButton {
            get {
                return ResourceManager.GetString("GridStringId.FilterPanelCustomizeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поместите сюда заголовок колонки для группировки.
        /// </summary>
        internal static string GridStringId_GridGroupPanelText {
            get {
                return ResourceManager.GetString("GridStringId.GridGroupPanelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нажмите здесь для добавления новой строки.
        /// </summary>
        internal static string GridStringId_GridNewRowText {
            get {
                return ResourceManager.GetString("GridStringId.GridNewRowText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Older;Last Month;Earlier this Month;Three Weeks Ago;Two Weeks Ago;Last Week;;;;;;;;Yesterday;Today;Tomorrow;;;;;;;;Next Week;Two Weeks Away;Three Weeks Away;Later this Month;Next Month;Beyond Next Month;.
        /// </summary>
        internal static string GridStringId_GridOutlookIntervals {
            get {
                return ResourceManager.GetString("GridStringId.GridOutlookIntervals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки вида были изменены.
        ///Вы хотите сохранить изменения?.
        /// </summary>
        internal static string GridStringId_LayoutModifiedWarning {
            get {
                return ResourceManager.GetString("GridStringId.LayoutModifiedWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Применить.
        /// </summary>
        internal static string GridStringId_LayoutViewButtonApply {
            get {
                return ResourceManager.GetString("GridStringId.LayoutViewButtonApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Отменить.
        /// </summary>
        internal static string GridStringId_LayoutViewButtonCancel {
            get {
                return ResourceManager.GetString("GridStringId.LayoutViewButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Скрыть настройки.
        /// </summary>
        internal static string GridStringId_LayoutViewButtonCustomizeHide {
            get {
                return ResourceManager.GetString("GridStringId.LayoutViewButtonCustomizeHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Показать настройки.
        /// </summary>
        internal static string GridStringId_LayoutViewButtonCustomizeShow {
            get {
                return ResourceManager.GetString("GridStringId.LayoutViewButtonCustomizeShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Загрузить настройки вида....
        /// </summary>
        internal static string GridStringId_LayoutViewButtonLoadLayout {
            get {
                return ResourceManager.GetString("GridStringId.LayoutViewButtonLoadLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Ok.
        /// </summary>
        internal static string GridStringId_LayoutViewButtonOk {
            get {
                return ResourceManager.GetString("GridStringId.LayoutViewButtonOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Показать еще карточки.
        /// </summary>
        internal static string GridStringId_LayoutViewButtonPreview {
            get {
                return ResourceManager.GetString("GridStringId.LayoutViewButtonPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Восстановить шаблон карточки.
        /// </summary>
        internal static string GridStringId_LayoutViewButtonReset {
            get {
                return ResourceManager.GetString("GridStringId.LayoutViewButtonReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Сохранить настройки вида....
        /// </summary>
        internal static string GridStringId_LayoutViewButtonSaveLayout {
            get {
                return ResourceManager.GetString("GridStringId.LayoutViewButtonSaveLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Уменьшить шаблон карточки.
        /// </summary>
        internal static string GridStringId_LayoutViewButtonShrinkToMinimum {
            get {
                return ResourceManager.GetString("GridStringId.LayoutViewButtonShrinkToMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carousel Mode.
        /// </summary>
        internal static string GridStringId_LayoutViewCarouselModeBtnHint {
            get {
                return ResourceManager.GetString("GridStringId.LayoutViewCarouselModeBtnHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Восстановить вид.
        /// </summary>
        internal static string GridStringId_LayoutViewCloseZoomBtnHintClose {
            get {
                return ResourceManager.GetString("GridStringId.LayoutViewCloseZoomBtnHintClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Максимум деталей.
        /// </summary>
        internal static string GridStringId_LayoutViewCloseZoomBtnHintZoom {
            get {
                return ResourceManager.GetString("GridStringId.LayoutViewCloseZoomBtnHintZoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Одна колонка.
        /// </summary>
        internal static string GridStringId_LayoutViewColumnModeBtnHint {
            get {
                return ResourceManager.GetString("GridStringId.LayoutViewColumnModeBtnHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройка вида.
        /// </summary>
        internal static string GridStringId_LayoutViewCustomizationFormCaption {
            get {
                return ResourceManager.GetString("GridStringId.LayoutViewCustomizationFormCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customize the card layout using drag-and-drop and customization menu, and preview data in the View Layout page..
        /// </summary>
        internal static string GridStringId_LayoutViewCustomizationFormDescription {
            get {
                return ResourceManager.GetString("GridStringId.LayoutViewCustomizationFormDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки.
        /// </summary>
        internal static string GridStringId_LayoutViewCustomizeBtnHint {
            get {
                return ResourceManager.GetString("GridStringId.LayoutViewCustomizeBtnHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заголовки.
        /// </summary>
        internal static string GridStringId_LayoutViewGroupCaptions {
            get {
                return ResourceManager.GetString("GridStringId.LayoutViewGroupCaptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Карточки.
        /// </summary>
        internal static string GridStringId_LayoutViewGroupCards {
            get {
                return ResourceManager.GetString("GridStringId.LayoutViewGroupCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки.
        /// </summary>
        internal static string GridStringId_LayoutViewGroupCustomization {
            get {
                return ResourceManager.GetString("GridStringId.LayoutViewGroupCustomization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поля группировки.
        /// </summary>
        internal static string GridStringId_LayoutViewGroupFields {
            get {
                return ResourceManager.GetString("GridStringId.LayoutViewGroupFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скрытые элементы.
        /// </summary>
        internal static string GridStringId_LayoutViewGroupHiddenItems {
            get {
                return ResourceManager.GetString("GridStringId.LayoutViewGroupHiddenItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отступы.
        /// </summary>
        internal static string GridStringId_LayoutViewGroupIndents {
            get {
                return ResourceManager.GetString("GridStringId.LayoutViewGroupIndents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Интервалы группировки.
        /// </summary>
        internal static string GridStringId_LayoutViewGroupIntervals {
            get {
                return ResourceManager.GetString("GridStringId.LayoutViewGroupIntervals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вид группировки.
        /// </summary>
        internal static string GridStringId_LayoutViewGroupLayout {
            get {
                return ResourceManager.GetString("GridStringId.LayoutViewGroupLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Свойства группировок.
        /// </summary>
        internal static string GridStringId_LayoutViewGroupPropertyGrid {
            get {
                return ResourceManager.GetString("GridStringId.LayoutViewGroupPropertyGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вид дерева группировок.
        /// </summary>
        internal static string GridStringId_LayoutViewGroupTreeStructure {
            get {
                return ResourceManager.GetString("GridStringId.LayoutViewGroupTreeStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Просмотр.
        /// </summary>
        internal static string GridStringId_LayoutViewGroupView {
            get {
                return ResourceManager.GetString("GridStringId.LayoutViewGroupView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Hot-Tracking.
        /// </summary>
        internal static string GridStringId_LayoutViewLabelAllowFieldHotTracking {
            get {
                return ResourceManager.GetString("GridStringId.LayoutViewLabelAllowFieldHotTracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расположение заголовка поля:.
        /// </summary>
        internal static string GridStringId_LayoutViewLabelCaptionLocation {
            get {
                return ResourceManager.GetString("GridStringId.LayoutViewLabelCaptionLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Правила размещения:.
        /// </summary>
        internal static string GridStringId_LayoutViewLabelCardArrangeRule {
            get {
                return ResourceManager.GetString("GridStringId.LayoutViewLabelCardArrangeRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выравнивание границы карточки:.
        /// </summary>
        internal static string GridStringId_LayoutViewLabelCardEdgeAlignment {
            get {
                return ResourceManager.GetString("GridStringId.LayoutViewLabelCardEdgeAlignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расположение заголовка группы:.
        /// </summary>
        internal static string GridStringId_LayoutViewLabelGroupCaptionLocation {
            get {
                return ResourceManager.GetString("GridStringId.LayoutViewLabelGroupCaptionLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Горизонтальный интервал.
        /// </summary>
        internal static string GridStringId_LayoutViewLabelHorizontal {
            get {
                return ResourceManager.GetString("GridStringId.LayoutViewLabelHorizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заполнение.
        /// </summary>
        internal static string GridStringId_LayoutViewLabelPadding {
            get {
                return ResourceManager.GetString("GridStringId.LayoutViewLabelPadding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Видимость полосы прокрутки:.
        /// </summary>
        internal static string GridStringId_LayoutViewLabelScrollVisibility {
            get {
                return ResourceManager.GetString("GridStringId.LayoutViewLabelScrollVisibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показать рамку.
        /// </summary>
        internal static string GridStringId_LayoutViewLabelShowCardBorder {
            get {
                return ResourceManager.GetString("GridStringId.LayoutViewLabelShowCardBorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показать заголовок.
        /// </summary>
        internal static string GridStringId_LayoutViewLabelShowCardCaption {
            get {
                return ResourceManager.GetString("GridStringId.LayoutViewLabelShowCardCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показать кнопку &quot;Развернуть&quot;.
        /// </summary>
        internal static string GridStringId_LayoutViewLabelShowCardExpandButton {
            get {
                return ResourceManager.GetString("GridStringId.LayoutViewLabelShowCardExpandButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показать рамку.
        /// </summary>
        internal static string GridStringId_LayoutViewLabelShowFieldBorder {
            get {
                return ResourceManager.GetString("GridStringId.LayoutViewLabelShowFieldBorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показать подсказку.
        /// </summary>
        internal static string GridStringId_LayoutViewLabelShowFieldHint {
            get {
                return ResourceManager.GetString("GridStringId.LayoutViewLabelShowFieldHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показать панель фильтра:.
        /// </summary>
        internal static string GridStringId_LayoutViewLabelShowFilterPanel {
            get {
                return ResourceManager.GetString("GridStringId.LayoutViewLabelShowFilterPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показать панель заголовка.
        /// </summary>
        internal static string GridStringId_LayoutViewLabelShowHeaderPanel {
            get {
                return ResourceManager.GetString("GridStringId.LayoutViewLabelShowHeaderPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показать линии.
        /// </summary>
        internal static string GridStringId_LayoutViewLabelShowLines {
            get {
                return ResourceManager.GetString("GridStringId.LayoutViewLabelShowLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Интервал.
        /// </summary>
        internal static string GridStringId_LayoutViewLabelSpacing {
            get {
                return ResourceManager.GetString("GridStringId.LayoutViewLabelSpacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выравнивание текста заголовка поля:.
        /// </summary>
        internal static string GridStringId_LayoutViewLabelTextAlignment {
            get {
                return ResourceManager.GetString("GridStringId.LayoutViewLabelTextAlignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отступы текста.
        /// </summary>
        internal static string GridStringId_LayoutViewLabelTextIndent {
            get {
                return ResourceManager.GetString("GridStringId.LayoutViewLabelTextIndent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вертикальный интервал.
        /// </summary>
        internal static string GridStringId_LayoutViewLabelVertical {
            get {
                return ResourceManager.GetString("GridStringId.LayoutViewLabelVertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Режим просмотра:.
        /// </summary>
        internal static string GridStringId_LayoutViewLabelViewMode {
            get {
                return ResourceManager.GetString("GridStringId.LayoutViewLabelViewMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple Columns.
        /// </summary>
        internal static string GridStringId_LayoutViewMultiColumnModeBtnHint {
            get {
                return ResourceManager.GetString("GridStringId.LayoutViewMultiColumnModeBtnHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple Rows.
        /// </summary>
        internal static string GridStringId_LayoutViewMultiRowModeBtnHint {
            get {
                return ResourceManager.GetString("GridStringId.LayoutViewMultiRowModeBtnHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template Card.
        /// </summary>
        internal static string GridStringId_LayoutViewPageTemplateCard {
            get {
                return ResourceManager.GetString("GridStringId.LayoutViewPageTemplateCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Layout.
        /// </summary>
        internal static string GridStringId_LayoutViewPageViewLayout {
            get {
                return ResourceManager.GetString("GridStringId.LayoutViewPageViewLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Горизонтальная прокрутка.
        /// </summary>
        internal static string GridStringId_LayoutViewPanBtnHint {
            get {
                return ResourceManager.GetString("GridStringId.LayoutViewPanBtnHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Одна строка.
        /// </summary>
        internal static string GridStringId_LayoutViewRowModeBtnHint {
            get {
                return ResourceManager.GetString("GridStringId.LayoutViewRowModeBtnHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One Card.
        /// </summary>
        internal static string GridStringId_LayoutViewSingleModeBtnHint {
            get {
                return ResourceManager.GetString("GridStringId.LayoutViewSingleModeBtnHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разместить оптимально по колонке.
        /// </summary>
        internal static string GridStringId_MenuColumnBestFit {
            get {
                return ResourceManager.GetString("GridStringId.MenuColumnBestFit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разместить оптимально (по всем колонкам).
        /// </summary>
        internal static string GridStringId_MenuColumnBestFitAllColumns {
            get {
                return ResourceManager.GetString("GridStringId.MenuColumnBestFitAllColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Очистить фильтр.
        /// </summary>
        internal static string GridStringId_MenuColumnClearFilter {
            get {
                return ResourceManager.GetString("GridStringId.MenuColumnClearFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Очистить сортировку.
        /// </summary>
        internal static string GridStringId_MenuColumnClearSorting {
            get {
                return ResourceManager.GetString("GridStringId.MenuColumnClearSorting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбор колонок.
        /// </summary>
        internal static string GridStringId_MenuColumnColumnCustomization {
            get {
                return ResourceManager.GetString("GridStringId.MenuColumnColumnCustomization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фильтр.
        /// </summary>
        internal static string GridStringId_MenuColumnFilter {
            get {
                return ResourceManager.GetString("GridStringId.MenuColumnFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактор фильтра.
        /// </summary>
        internal static string GridStringId_MenuColumnFilterEditor {
            get {
                return ResourceManager.GetString("GridStringId.MenuColumnFilterEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Группировать по колонке.
        /// </summary>
        internal static string GridStringId_MenuColumnGroup {
            get {
                return ResourceManager.GetString("GridStringId.MenuColumnGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отключить панель группировки.
        /// </summary>
        internal static string GridStringId_MenuColumnGroupBox {
            get {
                return ResourceManager.GetString("GridStringId.MenuColumnGroupBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сортировка по возрастанию.
        /// </summary>
        internal static string GridStringId_MenuColumnSortAscending {
            get {
                return ResourceManager.GetString("GridStringId.MenuColumnSortAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сортировка по убыванию.
        /// </summary>
        internal static string GridStringId_MenuColumnSortDescending {
            get {
                return ResourceManager.GetString("GridStringId.MenuColumnSortDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разгруппировать.
        /// </summary>
        internal static string GridStringId_MenuColumnUnGroup {
            get {
                return ResourceManager.GetString("GridStringId.MenuColumnUnGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Среднее значение.
        /// </summary>
        internal static string GridStringId_MenuFooterAverage {
            get {
                return ResourceManager.GetString("GridStringId.MenuFooterAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сред.={0:#.##}.
        /// </summary>
        internal static string GridStringId_MenuFooterAverageFormat {
            get {
                return ResourceManager.GetString("GridStringId.MenuFooterAverageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество.
        /// </summary>
        internal static string GridStringId_MenuFooterCount {
            get {
                return ResourceManager.GetString("GridStringId.MenuFooterCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        internal static string GridStringId_MenuFooterCountFormat {
            get {
                return ResourceManager.GetString("GridStringId.MenuFooterCountFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество={0}.
        /// </summary>
        internal static string GridStringId_MenuFooterCountGroupFormat {
            get {
                return ResourceManager.GetString("GridStringId.MenuFooterCountGroupFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Условие={0}.
        /// </summary>
        internal static string GridStringId_MenuFooterCustomFormat {
            get {
                return ResourceManager.GetString("GridStringId.MenuFooterCustomFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Максимум.
        /// </summary>
        internal static string GridStringId_MenuFooterMax {
            get {
                return ResourceManager.GetString("GridStringId.MenuFooterMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Макс.={0}.
        /// </summary>
        internal static string GridStringId_MenuFooterMaxFormat {
            get {
                return ResourceManager.GetString("GridStringId.MenuFooterMaxFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Минимум.
        /// </summary>
        internal static string GridStringId_MenuFooterMin {
            get {
                return ResourceManager.GetString("GridStringId.MenuFooterMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мин.={0}.
        /// </summary>
        internal static string GridStringId_MenuFooterMinFormat {
            get {
                return ResourceManager.GetString("GridStringId.MenuFooterMinFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет.
        /// </summary>
        internal static string GridStringId_MenuFooterNone {
            get {
                return ResourceManager.GetString("GridStringId.MenuFooterNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сумма.
        /// </summary>
        internal static string GridStringId_MenuFooterSum {
            get {
                return ResourceManager.GetString("GridStringId.MenuFooterSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сум.={0:#.##}.
        /// </summary>
        internal static string GridStringId_MenuFooterSumFormat {
            get {
                return ResourceManager.GetString("GridStringId.MenuFooterSumFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Очистить группировку.
        /// </summary>
        internal static string GridStringId_MenuGroupPanelClearGrouping {
            get {
                return ResourceManager.GetString("GridStringId.MenuGroupPanelClearGrouping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Свернуть все группы.
        /// </summary>
        internal static string GridStringId_MenuGroupPanelFullCollapse {
            get {
                return ResourceManager.GetString("GridStringId.MenuGroupPanelFullCollapse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Развернуть все группы.
        /// </summary>
        internal static string GridStringId_MenuGroupPanelFullExpand {
            get {
                return ResourceManager.GetString("GridStringId.MenuGroupPanelFullExpand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Все).
        /// </summary>
        internal static string GridStringId_PopupFilterAll {
            get {
                return ResourceManager.GetString("GridStringId.PopupFilterAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Пустые).
        /// </summary>
        internal static string GridStringId_PopupFilterBlanks {
            get {
                return ResourceManager.GetString("GridStringId.PopupFilterBlanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Условие).
        /// </summary>
        internal static string GridStringId_PopupFilterCustom {
            get {
                return ResourceManager.GetString("GridStringId.PopupFilterCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Непустые).
        /// </summary>
        internal static string GridStringId_PopupFilterNonBlanks {
            get {
                return ResourceManager.GetString("GridStringId.PopupFilterNonBlanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки печати (Выделенный диапазон).
        /// </summary>
        internal static string GridStringId_PrintDesignerBandedView {
            get {
                return ResourceManager.GetString("GridStringId.PrintDesignerBandedView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Объединенный заголовок.
        /// </summary>
        internal static string GridStringId_PrintDesignerBandHeader {
            get {
                return ResourceManager.GetString("GridStringId.PrintDesignerBandHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки печати (Карточки).
        /// </summary>
        internal static string GridStringId_PrintDesignerCardView {
            get {
                return ResourceManager.GetString("GridStringId.PrintDesignerCardView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Установите различные опции печати для текущего вида..
        /// </summary>
        internal static string GridStringId_PrintDesignerDescription {
            get {
                return ResourceManager.GetString("GridStringId.PrintDesignerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки печати (Таблица).
        /// </summary>
        internal static string GridStringId_PrintDesignerGridView {
            get {
                return ResourceManager.GetString("GridStringId.PrintDesignerGridView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Settings (Layout View).
        /// </summary>
        internal static string GridStringId_PrintDesignerLayoutView {
            get {
                return ResourceManager.GetString("GridStringId.PrintDesignerLayoutView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Применить.
        /// </summary>
        internal static string StringId_Apply {
            get {
                return ResourceManager.GetString("StringId.Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назад.
        /// </summary>
        internal static string StringId_CalcButtonBack {
            get {
                return ResourceManager.GetString("StringId.CalcButtonBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C.
        /// </summary>
        internal static string StringId_CalcButtonC {
            get {
                return ResourceManager.GetString("StringId.CalcButtonC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CE.
        /// </summary>
        internal static string StringId_CalcButtonCE {
            get {
                return ResourceManager.GetString("StringId.CalcButtonCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MC.
        /// </summary>
        internal static string StringId_CalcButtonMC {
            get {
                return ResourceManager.GetString("StringId.CalcButtonMC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MR.
        /// </summary>
        internal static string StringId_CalcButtonMR {
            get {
                return ResourceManager.GetString("StringId.CalcButtonMR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MS.
        /// </summary>
        internal static string StringId_CalcButtonMS {
            get {
                return ResourceManager.GetString("StringId.CalcButtonMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M+.
        /// </summary>
        internal static string StringId_CalcButtonMx {
            get {
                return ResourceManager.GetString("StringId.CalcButtonMx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sqrt.
        /// </summary>
        internal static string StringId_CalcButtonSqrt {
            get {
                return ResourceManager.GetString("StringId.CalcButtonSqrt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculation Error.
        /// </summary>
        internal static string StringId_CalcError {
            get {
                return ResourceManager.GetString("StringId.CalcError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отменить.
        /// </summary>
        internal static string StringId_Cancel {
            get {
                return ResourceManager.GetString("StringId.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка.
        /// </summary>
        internal static string StringId_CaptionError {
            get {
                return ResourceManager.GetString("StringId.CaptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Включенные.
        /// </summary>
        internal static string StringId_CheckChecked {
            get {
                return ResourceManager.GetString("StringId.CheckChecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неопределенный.
        /// </summary>
        internal static string StringId_CheckIndeterminate {
            get {
                return ResourceManager.GetString("StringId.CheckIndeterminate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выключенные.
        /// </summary>
        internal static string StringId_CheckUnchecked {
            get {
                return ResourceManager.GetString("StringId.CheckUnchecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        internal static string StringId_ColorTabCustom {
            get {
                return ResourceManager.GetString("StringId.ColorTabCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        internal static string StringId_ColorTabSystem {
            get {
                return ResourceManager.GetString("StringId.ColorTabSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web.
        /// </summary>
        internal static string StringId_ColorTabWeb {
            get {
                return ResourceManager.GetString("StringId.ColorTabWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing control.
        /// </summary>
        internal static string StringId_ContainerAccessibleEditName {
            get {
                return ResourceManager.GetString("StringId.ContainerAccessibleEditName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No image data.
        /// </summary>
        internal static string StringId_DataEmpty {
            get {
                return ResourceManager.GetString("StringId.DataEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Очистить.
        /// </summary>
        internal static string StringId_DateEditClear {
            get {
                return ResourceManager.GetString("StringId.DateEditClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сегодня.
        /// </summary>
        internal static string StringId_DateEditToday {
            get {
                return ResourceManager.GetString("StringId.DateEditToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Любой из.
        /// </summary>
        internal static string StringId_FilterClauseAnyOf {
            get {
                return ResourceManager.GetString("StringId.FilterClauseAnyOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начинается с.
        /// </summary>
        internal static string StringId_FilterClauseBeginsWith {
            get {
                return ResourceManager.GetString("StringId.FilterClauseBeginsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Между.
        /// </summary>
        internal static string StringId_FilterClauseBetween {
            get {
                return ResourceManager.GetString("StringId.FilterClauseBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to И.
        /// </summary>
        internal static string StringId_FilterClauseBetweenAnd {
            get {
                return ResourceManager.GetString("StringId.FilterClauseBetweenAnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Содержит.
        /// </summary>
        internal static string StringId_FilterClauseContains {
            get {
                return ResourceManager.GetString("StringId.FilterClauseContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не содержит.
        /// </summary>
        internal static string StringId_FilterClauseDoesNotContain {
            get {
                return ResourceManager.GetString("StringId.FilterClauseDoesNotContain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не равно.
        /// </summary>
        internal static string StringId_FilterClauseDoesNotEqual {
            get {
                return ResourceManager.GetString("StringId.FilterClauseDoesNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заканчиватся на.
        /// </summary>
        internal static string StringId_FilterClauseEndsWith {
            get {
                return ResourceManager.GetString("StringId.FilterClauseEndsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Равно.
        /// </summary>
        internal static string StringId_FilterClauseEquals {
            get {
                return ResourceManager.GetString("StringId.FilterClauseEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Больше.
        /// </summary>
        internal static string StringId_FilterClauseGreater {
            get {
                return ResourceManager.GetString("StringId.FilterClauseGreater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Больше или равно.
        /// </summary>
        internal static string StringId_FilterClauseGreaterOrEqual {
            get {
                return ResourceManager.GetString("StringId.FilterClauseGreaterOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не пустые.
        /// </summary>
        internal static string StringId_FilterClauseIsNotNull {
            get {
                return ResourceManager.GetString("StringId.FilterClauseIsNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пустые.
        /// </summary>
        internal static string StringId_FilterClauseIsNull {
            get {
                return ResourceManager.GetString("StringId.FilterClauseIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Меньше.
        /// </summary>
        internal static string StringId_FilterClauseLess {
            get {
                return ResourceManager.GetString("StringId.FilterClauseLess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Меньше или равно.
        /// </summary>
        internal static string StringId_FilterClauseLessOrEqual {
            get {
                return ResourceManager.GetString("StringId.FilterClauseLessOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Содержит.
        /// </summary>
        internal static string StringId_FilterClauseLike {
            get {
                return ResourceManager.GetString("StringId.FilterClauseLike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ни один из.
        /// </summary>
        internal static string StringId_FilterClauseNoneOf {
            get {
                return ResourceManager.GetString("StringId.FilterClauseNoneOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не между.
        /// </summary>
        internal static string StringId_FilterClauseNotBetween {
            get {
                return ResourceManager.GetString("StringId.FilterClauseNotBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не содержит.
        /// </summary>
        internal static string StringId_FilterClauseNotLike {
            get {
                return ResourceManager.GetString("StringId.FilterClauseNotLike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Между.
        /// </summary>
        internal static string StringId_FilterCriteriaToStringBetween {
            get {
                return ResourceManager.GetString("StringId.FilterCriteriaToStringBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;.
        /// </summary>
        internal static string StringId_FilterCriteriaToStringBinaryOperatorBitwiseAnd {
            get {
                return ResourceManager.GetString("StringId.FilterCriteriaToStringBinaryOperatorBitwiseAnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to |.
        /// </summary>
        internal static string StringId_FilterCriteriaToStringBinaryOperatorBitwiseOr {
            get {
                return ResourceManager.GetString("StringId.FilterCriteriaToStringBinaryOperatorBitwiseOr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^.
        /// </summary>
        internal static string StringId_FilterCriteriaToStringBinaryOperatorBitwiseXor {
            get {
                return ResourceManager.GetString("StringId.FilterCriteriaToStringBinaryOperatorBitwiseXor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /.
        /// </summary>
        internal static string StringId_FilterCriteriaToStringBinaryOperatorDivide {
            get {
                return ResourceManager.GetString("StringId.FilterCriteriaToStringBinaryOperatorDivide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to =.
        /// </summary>
        internal static string StringId_FilterCriteriaToStringBinaryOperatorEqual {
            get {
                return ResourceManager.GetString("StringId.FilterCriteriaToStringBinaryOperatorEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;.
        /// </summary>
        internal static string StringId_FilterCriteriaToStringBinaryOperatorGreater {
            get {
                return ResourceManager.GetString("StringId.FilterCriteriaToStringBinaryOperatorGreater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;=.
        /// </summary>
        internal static string StringId_FilterCriteriaToStringBinaryOperatorGreaterOrEqual {
            get {
                return ResourceManager.GetString("StringId.FilterCriteriaToStringBinaryOperatorGreaterOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;.
        /// </summary>
        internal static string StringId_FilterCriteriaToStringBinaryOperatorLess {
            get {
                return ResourceManager.GetString("StringId.FilterCriteriaToStringBinaryOperatorLess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;=.
        /// </summary>
        internal static string StringId_FilterCriteriaToStringBinaryOperatorLessOrEqual {
            get {
                return ResourceManager.GetString("StringId.FilterCriteriaToStringBinaryOperatorLessOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Like.
        /// </summary>
        internal static string StringId_FilterCriteriaToStringBinaryOperatorLike {
            get {
                return ResourceManager.GetString("StringId.FilterCriteriaToStringBinaryOperatorLike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        internal static string StringId_FilterCriteriaToStringBinaryOperatorMinus {
            get {
                return ResourceManager.GetString("StringId.FilterCriteriaToStringBinaryOperatorMinus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %.
        /// </summary>
        internal static string StringId_FilterCriteriaToStringBinaryOperatorModulo {
            get {
                return ResourceManager.GetString("StringId.FilterCriteriaToStringBinaryOperatorModulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        internal static string StringId_FilterCriteriaToStringBinaryOperatorMultiply {
            get {
                return ResourceManager.GetString("StringId.FilterCriteriaToStringBinaryOperatorMultiply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;&gt;.
        /// </summary>
        internal static string StringId_FilterCriteriaToStringBinaryOperatorNotEqual {
            get {
                return ResourceManager.GetString("StringId.FilterCriteriaToStringBinaryOperatorNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +.
        /// </summary>
        internal static string StringId_FilterCriteriaToStringBinaryOperatorPlus {
            get {
                return ResourceManager.GetString("StringId.FilterCriteriaToStringBinaryOperatorPlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        internal static string StringId_FilterCriteriaToStringFunctionCustom {
            get {
                return ResourceManager.GetString("StringId.FilterCriteriaToStringFunctionCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iif.
        /// </summary>
        internal static string StringId_FilterCriteriaToStringFunctionIif {
            get {
                return ResourceManager.GetString("StringId.FilterCriteriaToStringFunctionIif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsNull.
        /// </summary>
        internal static string StringId_FilterCriteriaToStringFunctionIsNull {
            get {
                return ResourceManager.GetString("StringId.FilterCriteriaToStringFunctionIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Len.
        /// </summary>
        internal static string StringId_FilterCriteriaToStringFunctionLen {
            get {
                return ResourceManager.GetString("StringId.FilterCriteriaToStringFunctionLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lower.
        /// </summary>
        internal static string StringId_FilterCriteriaToStringFunctionLower {
            get {
                return ResourceManager.GetString("StringId.FilterCriteriaToStringFunctionLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string StringId_FilterCriteriaToStringFunctionNone {
            get {
                return ResourceManager.GetString("StringId.FilterCriteriaToStringFunctionNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Substring.
        /// </summary>
        internal static string StringId_FilterCriteriaToStringFunctionSubstring {
            get {
                return ResourceManager.GetString("StringId.FilterCriteriaToStringFunctionSubstring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trim.
        /// </summary>
        internal static string StringId_FilterCriteriaToStringFunctionTrim {
            get {
                return ResourceManager.GetString("StringId.FilterCriteriaToStringFunctionTrim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upper.
        /// </summary>
        internal static string StringId_FilterCriteriaToStringFunctionUpper {
            get {
                return ResourceManager.GetString("StringId.FilterCriteriaToStringFunctionUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to И.
        /// </summary>
        internal static string StringId_FilterCriteriaToStringGroupOperatorAnd {
            get {
                return ResourceManager.GetString("StringId.FilterCriteriaToStringGroupOperatorAnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Или.
        /// </summary>
        internal static string StringId_FilterCriteriaToStringGroupOperatorOr {
            get {
                return ResourceManager.GetString("StringId.FilterCriteriaToStringGroupOperatorOr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В.
        /// </summary>
        internal static string StringId_FilterCriteriaToStringIn {
            get {
                return ResourceManager.GetString("StringId.FilterCriteriaToStringIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Непустые.
        /// </summary>
        internal static string StringId_FilterCriteriaToStringIsNotNull {
            get {
                return ResourceManager.GetString("StringId.FilterCriteriaToStringIsNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Like.
        /// </summary>
        internal static string StringId_FilterCriteriaToStringNotLike {
            get {
                return ResourceManager.GetString("StringId.FilterCriteriaToStringNotLike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~.
        /// </summary>
        internal static string StringId_FilterCriteriaToStringUnaryOperatorBitwiseNot {
            get {
                return ResourceManager.GetString("StringId.FilterCriteriaToStringUnaryOperatorBitwiseNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пустые.
        /// </summary>
        internal static string StringId_FilterCriteriaToStringUnaryOperatorIsNull {
            get {
                return ResourceManager.GetString("StringId.FilterCriteriaToStringUnaryOperatorIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        internal static string StringId_FilterCriteriaToStringUnaryOperatorMinus {
            get {
                return ResourceManager.GetString("StringId.FilterCriteriaToStringUnaryOperatorMinus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не.
        /// </summary>
        internal static string StringId_FilterCriteriaToStringUnaryOperatorNot {
            get {
                return ResourceManager.GetString("StringId.FilterCriteriaToStringUnaryOperatorNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +.
        /// </summary>
        internal static string StringId_FilterCriteriaToStringUnaryOperatorPlus {
            get {
                return ResourceManager.GetString("StringId.FilterCriteriaToStringUnaryOperatorPlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;введите значение&gt;.
        /// </summary>
        internal static string StringId_FilterEmptyEnter {
            get {
                return ResourceManager.GetString("StringId.FilterEmptyEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;пустые&gt;.
        /// </summary>
        internal static string StringId_FilterEmptyValue {
            get {
                return ResourceManager.GetString("StringId.FilterEmptyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to И.
        /// </summary>
        internal static string StringId_FilterGroupAnd {
            get {
                return ResourceManager.GetString("StringId.FilterGroupAnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не И.
        /// </summary>
        internal static string StringId_FilterGroupNotAnd {
            get {
                return ResourceManager.GetString("StringId.FilterGroupNotAnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не Или.
        /// </summary>
        internal static string StringId_FilterGroupNotOr {
            get {
                return ResourceManager.GetString("StringId.FilterGroupNotOr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Или.
        /// </summary>
        internal static string StringId_FilterGroupOr {
            get {
                return ResourceManager.GetString("StringId.FilterGroupOr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Очистить все.
        /// </summary>
        internal static string StringId_FilterMenuClearAll {
            get {
                return ResourceManager.GetString("StringId.FilterMenuClearAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить условие.
        /// </summary>
        internal static string StringId_FilterMenuConditionAdd {
            get {
                return ResourceManager.GetString("StringId.FilterMenuConditionAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить группу.
        /// </summary>
        internal static string StringId_FilterMenuGroupAdd {
            get {
                return ResourceManager.GetString("StringId.FilterMenuGroupAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить группу.
        /// </summary>
        internal static string StringId_FilterMenuRowRemove {
            get {
                return ResourceManager.GetString("StringId.FilterMenuRowRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Показать все).
        /// </summary>
        internal static string StringId_FilterShowAll {
            get {
                return ResourceManager.GetString("StringId.FilterShowAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить новый элемент в список.
        /// </summary>
        internal static string StringId_FilterToolTipElementAdd {
            get {
                return ResourceManager.GetString("StringId.FilterToolTipElementAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Используйте кнопку &quot;Вставить&quot; или &quot;Добавить&quot;).
        /// </summary>
        internal static string StringId_FilterToolTipKeysAdd {
            get {
                return ResourceManager.GetString("StringId.FilterToolTipKeysAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ((Используйте кнопку &quot;Удалить&quot; или &quot;Вычесть&quot;).
        /// </summary>
        internal static string StringId_FilterToolTipKeysRemove {
            get {
                return ResourceManager.GetString("StringId.FilterToolTipKeysRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        internal static string StringId_FilterToolTipNodeAction {
            get {
                return ResourceManager.GetString("StringId.FilterToolTipNodeAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить новое условие в эту группу.
        /// </summary>
        internal static string StringId_FilterToolTipNodeAdd {
            get {
                return ResourceManager.GetString("StringId.FilterToolTipNodeAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить это условие.
        /// </summary>
        internal static string StringId_FilterToolTipNodeRemove {
            get {
                return ResourceManager.GetString("StringId.FilterToolTipNodeRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare with a value / another field&apos;s value.
        /// </summary>
        internal static string StringId_FilterToolTipValueType {
            get {
                return ResourceManager.GetString("StringId.FilterToolTipValueType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Пусто).
        /// </summary>
        internal static string StringId_ImagePopupEmpty {
            get {
                return ResourceManager.GetString("StringId.ImagePopupEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Изображение).
        /// </summary>
        internal static string StringId_ImagePopupPicture {
            get {
                return ResourceManager.GetString("StringId.ImagePopupPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверное значение.
        /// </summary>
        internal static string StringId_InvalidValueText {
            get {
                return ResourceManager.GetString("StringId.InvalidValueText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        internal static string StringId_LookUpColumnDefaultName {
            get {
                return ResourceManager.GetString("StringId.LookUpColumnDefaultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Не уст.&gt;.
        /// </summary>
        internal static string StringId_LookUpEditValueIsNull {
            get {
                return ResourceManager.GetString("StringId.LookUpEditValueIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid LookUpEdit EditValue type..
        /// </summary>
        internal static string StringId_LookUpInvalidEditValueType {
            get {
                return ResourceManager.GetString("StringId.LookUpInvalidEditValueType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы ввели неполное значение.  Хотите исправить это?
        ///	
        ///	
        ///	Да - вернутся к редактированию и исправить значение.
        ///	Нет - оставить текущее значение.
        ///	Отмена - вернуть предыдущее значение.
        ///	.
        /// </summary>
        internal static string StringId_MaskBoxValidateError {
            get {
                return ResourceManager.GetString("StringId.MaskBoxValidateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать.
        /// </summary>
        internal static string StringId_NavigatorAppendButtonHint {
            get {
                return ResourceManager.GetString("StringId.NavigatorAppendButtonHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отменить.
        /// </summary>
        internal static string StringId_NavigatorCancelEditButtonHint {
            get {
                return ResourceManager.GetString("StringId.NavigatorCancelEditButtonHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактировать.
        /// </summary>
        internal static string StringId_NavigatorEditButtonHint {
            get {
                return ResourceManager.GetString("StringId.NavigatorEditButtonHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        internal static string StringId_NavigatorEndEditButtonHint {
            get {
                return ResourceManager.GetString("StringId.NavigatorEndEditButtonHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Первый.
        /// </summary>
        internal static string StringId_NavigatorFirstButtonHint {
            get {
                return ResourceManager.GetString("StringId.NavigatorFirstButtonHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Последний.
        /// </summary>
        internal static string StringId_NavigatorLastButtonHint {
            get {
                return ResourceManager.GetString("StringId.NavigatorLastButtonHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Следующий.
        /// </summary>
        internal static string StringId_NavigatorNextButtonHint {
            get {
                return ResourceManager.GetString("StringId.NavigatorNextButtonHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Следующая страница.
        /// </summary>
        internal static string StringId_NavigatorNextPageButtonHint {
            get {
                return ResourceManager.GetString("StringId.NavigatorNextPageButtonHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предыдущий.
        /// </summary>
        internal static string StringId_NavigatorPreviousButtonHint {
            get {
                return ResourceManager.GetString("StringId.NavigatorPreviousButtonHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предыдущая страница.
        /// </summary>
        internal static string StringId_NavigatorPreviousPageButtonHint {
            get {
                return ResourceManager.GetString("StringId.NavigatorPreviousPageButtonHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        internal static string StringId_NavigatorRemoveButtonHint {
            get {
                return ResourceManager.GetString("StringId.NavigatorRemoveButtonHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запись {0} из {1}.
        /// </summary>
        internal static string StringId_NavigatorTextStringFormat {
            get {
                return ResourceManager.GetString("StringId.NavigatorTextStringFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Недопустимая длина массива.
        /// </summary>
        internal static string StringId_NotValidArrayLength {
            get {
                return ResourceManager.GetString("StringId.NotValidArrayLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string StringId_OK {
            get {
                return ResourceManager.GetString("StringId.OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно скопировать изображение.
        /// </summary>
        internal static string StringId_PictureEditCopyImageError {
            get {
                return ResourceManager.GetString("StringId.PictureEditCopyImageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Копировать.
        /// </summary>
        internal static string StringId_PictureEditMenuCopy {
            get {
                return ResourceManager.GetString("StringId.PictureEditMenuCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вырезать.
        /// </summary>
        internal static string StringId_PictureEditMenuCut {
            get {
                return ResourceManager.GetString("StringId.PictureEditMenuCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        internal static string StringId_PictureEditMenuDelete {
            get {
                return ResourceManager.GetString("StringId.PictureEditMenuDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузить.
        /// </summary>
        internal static string StringId_PictureEditMenuLoad {
            get {
                return ResourceManager.GetString("StringId.PictureEditMenuLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вставить.
        /// </summary>
        internal static string StringId_PictureEditMenuPaste {
            get {
                return ResourceManager.GetString("StringId.PictureEditMenuPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        internal static string StringId_PictureEditMenuSave {
            get {
                return ResourceManager.GetString("StringId.PictureEditMenuSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неправильный формат изображения.
        /// </summary>
        internal static string StringId_PictureEditOpenFileError {
            get {
                return ResourceManager.GetString("StringId.PictureEditOpenFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open error.
        /// </summary>
        internal static string StringId_PictureEditOpenFileErrorCaption {
            get {
                return ResourceManager.GetString("StringId.PictureEditOpenFileErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitmap Files (*.bmp)|*.bmp|Graphics Interchange Format (*.gif)|*.gif|JPEG File Interchange Format (*.jpg;*.jpeg)|*.jpg;*.jpeg|Icon Files (*.ico)|*.ico|All Picture Files |*.bmp;*.gif;*.jpg;*.jpeg;*.ico;*.png;*.tif|All Files |*.*.
        /// </summary>
        internal static string StringId_PictureEditOpenFileFilter {
            get {
                return ResourceManager.GetString("StringId.PictureEditOpenFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыть.
        /// </summary>
        internal static string StringId_PictureEditOpenFileTitle {
            get {
                return ResourceManager.GetString("StringId.PictureEditOpenFileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitmap Files (*.bmp)|*.bmp|Graphics Interchange Format (*.gif)|*.gif|JPEG File Interchange Format (*.jpg)|*.jpg.
        /// </summary>
        internal static string StringId_PictureEditSaveFileFilter {
            get {
                return ResourceManager.GetString("StringId.PictureEditSaveFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить как.
        /// </summary>
        internal static string StringId_PictureEditSaveFileTitle {
            get {
                return ResourceManager.GetString("StringId.PictureEditSaveFileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предварительный просмотр:.
        /// </summary>
        internal static string StringId_PreviewPanelText {
            get {
                return ResourceManager.GetString("StringId.PreviewPanelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закрыть.
        /// </summary>
        internal static string StringId_TabHeaderButtonClose {
            get {
                return ResourceManager.GetString("StringId.TabHeaderButtonClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прокрутить вправо.
        /// </summary>
        internal static string StringId_TabHeaderButtonNext {
            get {
                return ResourceManager.GetString("StringId.TabHeaderButtonNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прокрутить влево.
        /// </summary>
        internal static string StringId_TabHeaderButtonPrev {
            get {
                return ResourceManager.GetString("StringId.TabHeaderButtonPrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Копировать.
        /// </summary>
        internal static string StringId_TextEditMenuCopy {
            get {
                return ResourceManager.GetString("StringId.TextEditMenuCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Вырезать.
        /// </summary>
        internal static string StringId_TextEditMenuCut {
            get {
                return ResourceManager.GetString("StringId.TextEditMenuCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Удалить.
        /// </summary>
        internal static string StringId_TextEditMenuDelete {
            get {
                return ResourceManager.GetString("StringId.TextEditMenuDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Вставить.
        /// </summary>
        internal static string StringId_TextEditMenuPaste {
            get {
                return ResourceManager.GetString("StringId.TextEditMenuPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Выбрать все.
        /// </summary>
        internal static string StringId_TextEditMenuSelectAll {
            get {
                return ResourceManager.GetString("StringId.TextEditMenuSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Отменить.
        /// </summary>
        internal static string StringId_TextEditMenuUndo {
            get {
                return ResourceManager.GetString("StringId.TextEditMenuUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This control does not support transparent background colors.
        /// </summary>
        internal static string StringId_TransparentBackColorNotSupported {
            get {
                return ResourceManager.GetString("StringId.TransparentBackColorNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неизвестный формат изображения.
        /// </summary>
        internal static string StringId_UnknownPictureFormat {
            get {
                return ResourceManager.GetString("StringId.UnknownPictureFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Прекратить.
        /// </summary>
        internal static string StringId_XtraMessageBoxAbortButtonText {
            get {
                return ResourceManager.GetString("StringId.XtraMessageBoxAbortButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Отменить.
        /// </summary>
        internal static string StringId_XtraMessageBoxCancelButtonText {
            get {
                return ResourceManager.GetString("StringId.XtraMessageBoxCancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Игнорировать.
        /// </summary>
        internal static string StringId_XtraMessageBoxIgnoreButtonText {
            get {
                return ResourceManager.GetString("StringId.XtraMessageBoxIgnoreButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Нет.
        /// </summary>
        internal static string StringId_XtraMessageBoxNoButtonText {
            get {
                return ResourceManager.GetString("StringId.XtraMessageBoxNoButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;OK.
        /// </summary>
        internal static string StringId_XtraMessageBoxOkButtonText {
            get {
                return ResourceManager.GetString("StringId.XtraMessageBoxOkButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Повторить.
        /// </summary>
        internal static string StringId_XtraMessageBoxRetryButtonText {
            get {
                return ResourceManager.GetString("StringId.XtraMessageBoxRetryButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Да.
        /// </summary>
        internal static string StringId_XtraMessageBoxYesButtonText {
            get {
                return ResourceManager.GetString("StringId.XtraMessageBoxYesButtonText", resourceCulture);
            }
        }
    }
}
