//----------------------------------------------------------------------------------------
// patterns & practices - Smart Client Software Factory - Guidance Package
//
// This file was generated by this guidance package as part of the solution template
//
// The FormShell class represent the main form of your application.
// 
// For more information see: 
// ms-help://MS.VSCC.v80/MS.VSIPCC.v80/ms.scsf.2006jun/SCSF/html/03-210-Creating%20a%20Smart%20Client%20Solution.htm
//
// Latest version of this Guidance Package: http://go.microsoft.com/fwlink/?LinkId=62182
//----------------------------------------------------------------------------------------

using System.Windows.Forms;

using Taumis.EnterpriseLibrary.Win.Constants;

using Taumis.Infrastructure.Interface.Constants;

namespace Taumis.Infrastructure.Shell
{
    /// <summary>
    /// Main application shell view.
    /// </summary>
    public partial class ShellForm : Form
    {

		public ShellForm()
        {
            InitializeComponent();

            _layoutWorkspace.Name = CommonWorkspaceNames.LayoutWorkspace;

            _statusWorkspace.Name = CommonWorkspaceNames.StatusWorkspace;
			
			this.IsMdiContainer = true;
            this.Text = "Aurora 2073";
        }

    }
}
