//----------------------------------------------------------------------------------------
// patterns & practices - Smart Client Software Factory - Guidance Package
//
// This file was generated by this guidance package as part of the solution template
//
// The FormShell class represent the main form of your application.
// 
// For more information see: 
// ms-help://MS.VSCC.v80/MS.VSIPCC.v80/ms.scsf.2006jun/SCSF/html/03-210-Creating%20a%20Smart%20Client%20Solution.htm
//
// Latest version of this Guidance Package: http://go.microsoft.com/fwlink/?LinkId=62182
//----------------------------------------------------------------------------------------

namespace Taumis.Infrastructure.Shell
{
    partial class ShellForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(ShellForm));
            this._layoutWorkspace = new Microsoft.Practices.CompositeUI.WinForms.DeckWorkspace();
            this._statusWorkspace = new Microsoft.Practices.CompositeUI.WinForms.DeckWorkspace();
            this.SuspendLayout();
            // 
            // _layoutWorkspace
            // 
            this._layoutWorkspace.Dock = System.Windows.Forms.DockStyle.Top;
            this._layoutWorkspace.Location = new System.Drawing.Point(0, 0);
            this._layoutWorkspace.Name = "_layoutWorkspace";
            this._layoutWorkspace.Size = new System.Drawing.Size(698, 80);
            this._layoutWorkspace.TabIndex = 12;
            this._layoutWorkspace.Text = "deckWorkspace1";
            // 
            // _statusWorkspace
            // 
            this._statusWorkspace.Dock = System.Windows.Forms.DockStyle.Bottom;
            this._statusWorkspace.Location = new System.Drawing.Point(0, 494);
            this._statusWorkspace.Name = "_statusWorkspace";
            this._statusWorkspace.Size = new System.Drawing.Size(698, 22);
            this._statusWorkspace.TabIndex = 14;
            // 
            // ShellForm
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(698, 516);
            this.Controls.Add(this._statusWorkspace);
            this.Controls.Add(this._layoutWorkspace);
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.IsMdiContainer = true;
            this.Name = "ShellForm";
            this.Text = "Aurora";
            this.WindowState = System.Windows.Forms.FormWindowState.Maximized;
            this.ResumeLayout(false);

        }

        #endregion

		private Microsoft.Practices.CompositeUI.WinForms.DeckWorkspace _layoutWorkspace;
		private Microsoft.Practices.CompositeUI.WinForms.DeckWorkspace _statusWorkspace;

	}
}
