
//----------------------------------------------------------------------------------------
// patterns & practices - Smart Client Software Factory - Guidance Package
//
// This file was generated by the "Add View" recipe.
//
// For more information see: 
// ms-help://MS.VSCC.v80/MS.VSIPCC.v80/ms.practices.scsf.2007may/SCSF/html/02-09-010-ModelViewPresenter_MVP.htm
//
// Latest version of this Guidance Package: http://go.microsoft.com/fwlink/?LinkId=62182
//----------------------------------------------------------------------------------------

namespace Taumis.Alpha.WinClient.Aurora.Modules.Accounting.Customers
{
    partial class TabbedView
    {

        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                if (components != null)
                    components.Dispose();
            }

            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this._tabWorkspace = new Microsoft.Practices.CompositeUI.WinForms.TabWorkspace();
            this.tabList = new System.Windows.Forms.TabPage();
            this.viewSmartPartPlaceholder = new Microsoft.Practices.CompositeUI.WinForms.SmartPartPlaceholder();
            this.topViewSmartPartPlaceholder = new Microsoft.Practices.CompositeUI.WinForms.SmartPartPlaceholder();
            this.tabDetail = new System.Windows.Forms.TabPage();
            this.detailSmartPartPlaceholder = new Microsoft.Practices.CompositeUI.WinForms.SmartPartPlaceholder();
            this.tabCustomerPoses = new System.Windows.Forms.TabPage();
            this.smartPartPlaceholder1 = new Microsoft.Practices.CompositeUI.WinForms.SmartPartPlaceholder();
            this.counterSplitContainer = new System.Windows.Forms.SplitContainer();
            this.smartPartPlaceholder2 = new Microsoft.Practices.CompositeUI.WinForms.SmartPartPlaceholder();
            this.smartPartPlaceholder3 = new Microsoft.Practices.CompositeUI.WinForms.SmartPartPlaceholder();
            this.tabChargesAndPayments = new System.Windows.Forms.TabPage();
            this.PaymentsAndChargesSmartPartPlaceholder = new Microsoft.Practices.CompositeUI.WinForms.SmartPartPlaceholder();
            this.groupBox1 = new System.Windows.Forms.GroupBox();
            this.groupBox2 = new System.Windows.Forms.GroupBox();
            this._tabWorkspace.SuspendLayout();
            this.tabList.SuspendLayout();
            this.tabDetail.SuspendLayout();
            this.tabCustomerPoses.SuspendLayout();
            this.counterSplitContainer.Panel1.SuspendLayout();
            this.counterSplitContainer.Panel2.SuspendLayout();
            this.counterSplitContainer.SuspendLayout();
            this.tabChargesAndPayments.SuspendLayout();
            this.groupBox1.SuspendLayout();
            this.groupBox2.SuspendLayout();
            this.SuspendLayout();
            // 
            // _tabWorkspace
            // 
            this._tabWorkspace.Controls.Add(this.tabList);
            this._tabWorkspace.Controls.Add(this.tabDetail);
            this._tabWorkspace.Controls.Add(this.tabCustomerPoses);
            this._tabWorkspace.Controls.Add(this.tabChargesAndPayments);
            this._tabWorkspace.Dock = System.Windows.Forms.DockStyle.Fill;
            this._tabWorkspace.Location = new System.Drawing.Point(0, 0);
            this._tabWorkspace.Name = "_tabWorkspace";
            this._tabWorkspace.SelectedIndex = 0;
            this._tabWorkspace.Size = new System.Drawing.Size(720, 454);
            this._tabWorkspace.TabIndex = 1;
            // 
            // tabList
            // 
            this.tabList.Controls.Add(this.viewSmartPartPlaceholder);
            this.tabList.Controls.Add(this.topViewSmartPartPlaceholder);
            this.tabList.Location = new System.Drawing.Point(4, 22);
            this.tabList.Name = "tabList";
            this.tabList.Padding = new System.Windows.Forms.Padding(3);
            this.tabList.Size = new System.Drawing.Size(712, 428);
            this.tabList.TabIndex = 0;
            this.tabList.Text = "Обзор";
            this.tabList.UseVisualStyleBackColor = true;
            // 
            // viewSmartPartPlaceholder
            // 
            this.viewSmartPartPlaceholder.BackColor = System.Drawing.Color.Transparent;
            this.viewSmartPartPlaceholder.Dock = System.Windows.Forms.DockStyle.Fill;
            this.viewSmartPartPlaceholder.Location = new System.Drawing.Point(3, 108);
            this.viewSmartPartPlaceholder.Name = "viewSmartPartPlaceholder";
            this.viewSmartPartPlaceholder.Size = new System.Drawing.Size(706, 317);
            this.viewSmartPartPlaceholder.SmartPartName = "ListView";
            this.viewSmartPartPlaceholder.TabIndex = 0;
            // 
            // topViewSmartPartPlaceholder
            // 
            this.topViewSmartPartPlaceholder.BackColor = System.Drawing.Color.Transparent;
            this.topViewSmartPartPlaceholder.Dock = System.Windows.Forms.DockStyle.Top;
            this.topViewSmartPartPlaceholder.Location = new System.Drawing.Point(3, 3);
            this.topViewSmartPartPlaceholder.Margin = new System.Windows.Forms.Padding(0);
            this.topViewSmartPartPlaceholder.Name = "topViewSmartPartPlaceholder";
            this.topViewSmartPartPlaceholder.Size = new System.Drawing.Size(706, 105);
            this.topViewSmartPartPlaceholder.SmartPartName = "TopView";
            this.topViewSmartPartPlaceholder.TabIndex = 4;
            // 
            // tabDetail
            // 
            this.tabDetail.Controls.Add(this.detailSmartPartPlaceholder);
            this.tabDetail.Location = new System.Drawing.Point(4, 22);
            this.tabDetail.Name = "tabDetail";
            this.tabDetail.Padding = new System.Windows.Forms.Padding(3);
            this.tabDetail.Size = new System.Drawing.Size(712, 428);
            this.tabDetail.TabIndex = 1;
            this.tabDetail.Text = "Детали";
            this.tabDetail.UseVisualStyleBackColor = true;
            // 
            // detailSmartPartPlaceholder
            // 
            this.detailSmartPartPlaceholder.BackColor = System.Drawing.Color.Transparent;
            this.detailSmartPartPlaceholder.Dock = System.Windows.Forms.DockStyle.Fill;
            this.detailSmartPartPlaceholder.Location = new System.Drawing.Point(3, 3);
            this.detailSmartPartPlaceholder.Name = "detailSmartPartPlaceholder";
            this.detailSmartPartPlaceholder.Size = new System.Drawing.Size(706, 422);
            this.detailSmartPartPlaceholder.SmartPartName = "ItemView";
            this.detailSmartPartPlaceholder.TabIndex = 0;
            // 
            // tabCustomerPoses
            // 
            this.tabCustomerPoses.Controls.Add(this.smartPartPlaceholder1);
            this.tabCustomerPoses.Controls.Add(this.counterSplitContainer);
            this.tabCustomerPoses.Location = new System.Drawing.Point(4, 22);
            this.tabCustomerPoses.Name = "tabCustomerPoses";
            this.tabCustomerPoses.Size = new System.Drawing.Size(712, 428);
            this.tabCustomerPoses.TabIndex = 3;
            this.tabCustomerPoses.Text = "Услуги";
            this.tabCustomerPoses.UseVisualStyleBackColor = true;
            // 
            // smartPartPlaceholder1
            // 
            this.smartPartPlaceholder1.BackColor = System.Drawing.Color.Transparent;
            this.smartPartPlaceholder1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.smartPartPlaceholder1.Location = new System.Drawing.Point(0, 0);
            this.smartPartPlaceholder1.Name = "smartPartPlaceholder1";
            this.smartPartPlaceholder1.Size = new System.Drawing.Size(712, 268);
            this.smartPartPlaceholder1.SmartPartName = "CustomerPosListView";
            this.smartPartPlaceholder1.TabIndex = 1;
            // 
            // counterSplitContainer
            // 
            this.counterSplitContainer.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.counterSplitContainer.IsSplitterFixed = true;
            this.counterSplitContainer.Location = new System.Drawing.Point(0, 268);
            this.counterSplitContainer.Name = "counterSplitContainer";
            // 
            // counterSplitContainer.Panel1
            // 
            this.counterSplitContainer.Panel1.Controls.Add(this.groupBox1);
            // 
            // counterSplitContainer.Panel2
            // 
            this.counterSplitContainer.Panel2.Controls.Add(this.groupBox2);
            this.counterSplitContainer.Size = new System.Drawing.Size(712, 160);
            this.counterSplitContainer.SplitterDistance = 356;
            this.counterSplitContainer.SplitterWidth = 2;
            this.counterSplitContainer.TabIndex = 4;
            // 
            // smartPartPlaceholder2
            // 
            this.smartPartPlaceholder2.BackColor = System.Drawing.Color.Transparent;
            this.smartPartPlaceholder2.Dock = System.Windows.Forms.DockStyle.Fill;
            this.smartPartPlaceholder2.Location = new System.Drawing.Point(3, 16);
            this.smartPartPlaceholder2.Name = "smartPartPlaceholder2";
            this.smartPartPlaceholder2.Size = new System.Drawing.Size(350, 141);
            this.smartPartPlaceholder2.SmartPartName = "CounterView";
            this.smartPartPlaceholder2.TabIndex = 2;
            // 
            // smartPartPlaceholder3
            // 
            this.smartPartPlaceholder3.BackColor = System.Drawing.Color.Transparent;
            this.smartPartPlaceholder3.Dock = System.Windows.Forms.DockStyle.Fill;
            this.smartPartPlaceholder3.Location = new System.Drawing.Point(3, 16);
            this.smartPartPlaceholder3.Name = "smartPartPlaceholder3";
            this.smartPartPlaceholder3.Size = new System.Drawing.Size(348, 141);
            this.smartPartPlaceholder3.SmartPartName = "CounterValueView";
            this.smartPartPlaceholder3.TabIndex = 3;
            // 
            // tabChargesAndPayments
            // 
            this.tabChargesAndPayments.Controls.Add(this.PaymentsAndChargesSmartPartPlaceholder);
            this.tabChargesAndPayments.Location = new System.Drawing.Point(4, 22);
            this.tabChargesAndPayments.Name = "tabChargesAndPayments";
            this.tabChargesAndPayments.Size = new System.Drawing.Size(712, 428);
            this.tabChargesAndPayments.TabIndex = 2;
            this.tabChargesAndPayments.Text = "Платежи и начисления";
            this.tabChargesAndPayments.UseVisualStyleBackColor = true;
            // 
            // PaymentsAndChargesSmartPartPlaceholder
            // 
            this.PaymentsAndChargesSmartPartPlaceholder.BackColor = System.Drawing.Color.Transparent;
            this.PaymentsAndChargesSmartPartPlaceholder.Dock = System.Windows.Forms.DockStyle.Fill;
            this.PaymentsAndChargesSmartPartPlaceholder.Location = new System.Drawing.Point(0, 0);
            this.PaymentsAndChargesSmartPartPlaceholder.Name = "PaymentsAndChargesSmartPartPlaceholder";
            this.PaymentsAndChargesSmartPartPlaceholder.Size = new System.Drawing.Size(712, 428);
            this.PaymentsAndChargesSmartPartPlaceholder.SmartPartName = "PaymentsAndChargesView";
            this.PaymentsAndChargesSmartPartPlaceholder.TabIndex = 1;
            // 
            // groupBox1
            // 
            this.groupBox1.Controls.Add(this.smartPartPlaceholder2);
            this.groupBox1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.groupBox1.Location = new System.Drawing.Point(0, 0);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new System.Drawing.Size(356, 160);
            this.groupBox1.TabIndex = 3;
            this.groupBox1.TabStop = false;
            this.groupBox1.Text = "Приборы учета";
            // 
            // groupBox2
            // 
            this.groupBox2.Controls.Add(this.smartPartPlaceholder3);
            this.groupBox2.Dock = System.Windows.Forms.DockStyle.Fill;
            this.groupBox2.Location = new System.Drawing.Point(0, 0);
            this.groupBox2.Name = "groupBox2";
            this.groupBox2.Size = new System.Drawing.Size(354, 160);
            this.groupBox2.TabIndex = 4;
            this.groupBox2.TabStop = false;
            this.groupBox2.Text = "Показания";
            // 
            // TabbedView
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Controls.Add(this._tabWorkspace);
            this.Name = "TabbedView";
            this.Size = new System.Drawing.Size(720, 454);
            this._tabWorkspace.ResumeLayout(false);
            this.tabList.ResumeLayout(false);
            this.tabDetail.ResumeLayout(false);
            this.tabCustomerPoses.ResumeLayout(false);
            this.counterSplitContainer.Panel1.ResumeLayout(false);
            this.counterSplitContainer.Panel2.ResumeLayout(false);
            this.counterSplitContainer.ResumeLayout(false);
            this.tabChargesAndPayments.ResumeLayout(false);
            this.groupBox1.ResumeLayout(false);
            this.groupBox2.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private Microsoft.Practices.CompositeUI.WinForms.TabWorkspace _tabWorkspace;
        private System.Windows.Forms.TabPage tabList;
        private Microsoft.Practices.CompositeUI.WinForms.SmartPartPlaceholder viewSmartPartPlaceholder;
        private System.Windows.Forms.TabPage tabDetail;
        private Microsoft.Practices.CompositeUI.WinForms.SmartPartPlaceholder detailSmartPartPlaceholder;
        private System.Windows.Forms.TabPage tabChargesAndPayments;
        private Microsoft.Practices.CompositeUI.WinForms.SmartPartPlaceholder PaymentsAndChargesSmartPartPlaceholder;
        private Microsoft.Practices.CompositeUI.WinForms.SmartPartPlaceholder topViewSmartPartPlaceholder;
        private System.Windows.Forms.TabPage tabCustomerPoses;
        private Microsoft.Practices.CompositeUI.WinForms.SmartPartPlaceholder smartPartPlaceholder1;
        private Microsoft.Practices.CompositeUI.WinForms.SmartPartPlaceholder smartPartPlaceholder3;
        private Microsoft.Practices.CompositeUI.WinForms.SmartPartPlaceholder smartPartPlaceholder2;
        private System.Windows.Forms.SplitContainer counterSplitContainer;
        private System.Windows.Forms.GroupBox groupBox1;
        private System.Windows.Forms.GroupBox groupBox2;
    }
}

