
//----------------------------------------------------------------------------------------
// patterns & practices - Smart Client Software Factory - Guidance Package
//
// This file was generated by the "Add View" recipe.
//
// For more information see: 
// ms-help://MS.VSCC.v80/MS.VSIPCC.v80/ms.practices.scsf.2007may/SCSF/html/02-09-010-ModelViewPresenter_MVP.htm
//
// Latest version of this Guidance Package: http://go.microsoft.com/fwlink/?LinkId=62182
//----------------------------------------------------------------------------------------

namespace Taumis.Alpha.WinClient.Aurora.Modules.Accounting.Customers
{
    partial class ListView
    {

        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                if (components != null)
                    components.Dispose();
            }

            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.gridControlOfListView = new DevExpress.XtraGrid.GridControl();
            this.gridViewOfListView = new DevExpress.XtraGrid.Views.Grid.GridView();
            this.IDColumn = new DevExpress.XtraGrid.Columns.GridColumn();
            this.AccountColumn = new DevExpress.XtraGrid.Columns.GridColumn();
            this.OwnerColumn = new DevExpress.XtraGrid.Columns.GridColumn();
            this.ResidentsNumberColumn = new DevExpress.XtraGrid.Columns.GridColumn();
            this.StreetColumn = new DevExpress.XtraGrid.Columns.GridColumn();
            this.HouseColumn = new DevExpress.XtraGrid.Columns.GridColumn();
            this.ApartmentColumn = new DevExpress.XtraGrid.Columns.GridColumn();
            this.SquareColumn = new DevExpress.XtraGrid.Columns.GridColumn();
            this.stateLookUpEdit = new DevExpress.XtraEditors.Repository.RepositoryItemLookUpEdit();
            this.isTransItemCheckEdit = new DevExpress.XtraEditors.Repository.RepositoryItemCheckEdit();
            this.isArchCheckEdit = new DevExpress.XtraEditors.Repository.RepositoryItemCheckEdit();
            this.FloorColumn = new DevExpress.XtraGrid.Columns.GridColumn();
            ((System.ComponentModel.ISupportInitialize)(this.gridControlOfListView)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.gridViewOfListView)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.stateLookUpEdit)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.isTransItemCheckEdit)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.isArchCheckEdit)).BeginInit();
            this.SuspendLayout();
            // 
            // gridControlOfListView
            // 
            this.gridControlOfListView.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.gridControlOfListView.EmbeddedNavigator.Buttons.Append.Enabled = false;
            this.gridControlOfListView.EmbeddedNavigator.Buttons.Append.Visible = false;
            this.gridControlOfListView.EmbeddedNavigator.Buttons.CancelEdit.Enabled = false;
            this.gridControlOfListView.EmbeddedNavigator.Buttons.CancelEdit.Visible = false;
            this.gridControlOfListView.EmbeddedNavigator.Buttons.Edit.Enabled = false;
            this.gridControlOfListView.EmbeddedNavigator.Buttons.Edit.Visible = false;
            this.gridControlOfListView.EmbeddedNavigator.Buttons.EndEdit.Enabled = false;
            this.gridControlOfListView.EmbeddedNavigator.Buttons.EndEdit.Visible = false;
            this.gridControlOfListView.EmbeddedNavigator.Buttons.Remove.Enabled = false;
            this.gridControlOfListView.EmbeddedNavigator.Buttons.Remove.Visible = false;
            this.gridControlOfListView.Location = new System.Drawing.Point(3, 3);
            this.gridControlOfListView.MainView = this.gridViewOfListView;
            this.gridControlOfListView.Name = "gridControlOfListView";
            this.gridControlOfListView.RepositoryItems.AddRange(new DevExpress.XtraEditors.Repository.RepositoryItem[] {
            this.stateLookUpEdit,
            this.isTransItemCheckEdit,
            this.isArchCheckEdit});
            this.gridControlOfListView.Size = new System.Drawing.Size(739, 376);
            this.gridControlOfListView.TabIndex = 0;
            this.gridControlOfListView.UseEmbeddedNavigator = true;
            this.gridControlOfListView.ViewCollection.AddRange(new DevExpress.XtraGrid.Views.Base.BaseView[] {
            this.gridViewOfListView});
            // 
            // gridViewOfListView
            // 
            this.gridViewOfListView.Appearance.HeaderPanel.Options.UseTextOptions = true;
            this.gridViewOfListView.Appearance.HeaderPanel.TextOptions.HAlignment = DevExpress.Utils.HorzAlignment.Center;
            this.gridViewOfListView.Appearance.HeaderPanel.TextOptions.VAlignment = DevExpress.Utils.VertAlignment.Center;
            this.gridViewOfListView.Columns.AddRange(new DevExpress.XtraGrid.Columns.GridColumn[] {
            this.IDColumn,
            this.AccountColumn,
            this.OwnerColumn,
            this.ResidentsNumberColumn,
            this.StreetColumn,
            this.HouseColumn,
            this.FloorColumn,
            this.ApartmentColumn,
            this.SquareColumn});
            this.gridViewOfListView.GridControl = this.gridControlOfListView;
            this.gridViewOfListView.Name = "gridViewOfListView";
            this.gridViewOfListView.OptionsBehavior.AllowIncrementalSearch = true;
            this.gridViewOfListView.OptionsBehavior.Editable = false;
            this.gridViewOfListView.OptionsSelection.MultiSelect = true;
            // 
            // IDColumn
            // 
            this.IDColumn.Caption = "ID";
            this.IDColumn.FieldName = "ID";
            this.IDColumn.Name = "IDColumn";
            // 
            // AccountColumn
            // 
            this.AccountColumn.Caption = "Лицевой счет";
            this.AccountColumn.FieldName = "Account";
            this.AccountColumn.Name = "AccountColumn";
            this.AccountColumn.Visible = true;
            this.AccountColumn.VisibleIndex = 0;
            this.AccountColumn.Width = 60;
            // 
            // OwnerColumn
            // 
            this.OwnerColumn.Caption = "Собственник";
            this.OwnerColumn.FieldName = "Owner";
            this.OwnerColumn.Name = "OwnerColumn";
            this.OwnerColumn.Visible = true;
            this.OwnerColumn.VisibleIndex = 1;
            this.OwnerColumn.Width = 98;
            // 
            // ResidentsNumberColumn
            // 
            this.ResidentsNumberColumn.Caption = "Жильцов";
            this.ResidentsNumberColumn.FieldName = "ResidentsNumber";
            this.ResidentsNumberColumn.Name = "ResidentsNumberColumn";
            this.ResidentsNumberColumn.Visible = true;
            this.ResidentsNumberColumn.VisibleIndex = 2;
            // 
            // StreetColumn
            // 
            this.StreetColumn.Caption = "Улица";
            this.StreetColumn.FieldName = "Street";
            this.StreetColumn.Name = "StreetColumn";
            this.StreetColumn.Visible = true;
            this.StreetColumn.VisibleIndex = 3;
            this.StreetColumn.Width = 120;
            // 
            // HouseColumn
            // 
            this.HouseColumn.Caption = "Дом";
            this.HouseColumn.FieldName = "House";
            this.HouseColumn.Name = "HouseColumn";
            this.HouseColumn.Visible = true;
            this.HouseColumn.VisibleIndex = 4;
            this.HouseColumn.Width = 120;
            // 
            // ApartmentColumn
            // 
            this.ApartmentColumn.Caption = "Квартира";
            this.ApartmentColumn.FieldName = "Apartment";
            this.ApartmentColumn.Name = "ApartmentColumn";
            this.ApartmentColumn.Visible = true;
            this.ApartmentColumn.VisibleIndex = 5;
            this.ApartmentColumn.Width = 183;
            // 
            // SquareColumn
            // 
            this.SquareColumn.Caption = "Общая площадь";
            this.SquareColumn.FieldName = "Square";
            this.SquareColumn.Name = "SquareColumn";
            this.SquareColumn.Visible = true;
            this.SquareColumn.VisibleIndex = 7;
            this.SquareColumn.Width = 55;
            // 
            // stateLookUpEdit
            // 
            this.stateLookUpEdit.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] {
            new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo)});
            this.stateLookUpEdit.Columns.AddRange(new DevExpress.XtraEditors.Controls.LookUpColumnInfo[] {
            new DevExpress.XtraEditors.Controls.LookUpColumnInfo("Aka", "Наименование"),
            new DevExpress.XtraEditors.Controls.LookUpColumnInfo("ID", "ID", 20, DevExpress.Utils.FormatType.None, "", false, DevExpress.Utils.HorzAlignment.Default),
            new DevExpress.XtraEditors.Controls.LookUpColumnInfo("Colour", "Цвет", 20, DevExpress.Utils.FormatType.Numeric, "", true, DevExpress.Utils.HorzAlignment.Default)});
            this.stateLookUpEdit.DisplayMember = "Aka";
            this.stateLookUpEdit.Name = "stateLookUpEdit";
            this.stateLookUpEdit.NullText = "<Не уст.>";
            this.stateLookUpEdit.ValueMember = "Aka";
            // 
            // isTransItemCheckEdit
            // 
            this.isTransItemCheckEdit.AutoHeight = false;
            this.isTransItemCheckEdit.Caption = "Check";
            this.isTransItemCheckEdit.Name = "isTransItemCheckEdit";
            this.isTransItemCheckEdit.NullStyle = DevExpress.XtraEditors.Controls.StyleIndeterminate.Unchecked;
            this.isTransItemCheckEdit.ValueChecked = "1";
            this.isTransItemCheckEdit.ValueUnchecked = "0";
            // 
            // isArchCheckEdit
            // 
            this.isArchCheckEdit.AutoHeight = false;
            this.isArchCheckEdit.Caption = "Check";
            this.isArchCheckEdit.Name = "isArchCheckEdit";
            this.isArchCheckEdit.NullStyle = DevExpress.XtraEditors.Controls.StyleIndeterminate.Unchecked;
            this.isArchCheckEdit.ValueChecked = "1";
            this.isArchCheckEdit.ValueUnchecked = "0";
            // 
            // FloorColumn
            // 
            this.FloorColumn.Caption = "Этаж";
            this.FloorColumn.FieldName = "Floor";
            this.FloorColumn.Name = "FloorColumn";
            this.FloorColumn.Visible = true;
            this.FloorColumn.VisibleIndex = 6;
            // 
            // ListView
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Controls.Add(this.gridControlOfListView);
            this.Name = "ListView";
            this.Size = new System.Drawing.Size(745, 382);
            ((System.ComponentModel.ISupportInitialize)(this.gridControlOfListView)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.gridViewOfListView)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.stateLookUpEdit)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.isTransItemCheckEdit)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.isArchCheckEdit)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private DevExpress.XtraGrid.GridControl gridControlOfListView;
        private DevExpress.XtraGrid.Views.Grid.GridView gridViewOfListView;
        private DevExpress.XtraGrid.Columns.GridColumn AccountColumn;
        private DevExpress.XtraGrid.Columns.GridColumn OwnerColumn;
        private DevExpress.XtraGrid.Columns.GridColumn IDColumn;
        private DevExpress.XtraEditors.Repository.RepositoryItemLookUpEdit stateLookUpEdit;
        private DevExpress.XtraGrid.Columns.GridColumn SquareColumn;
        private DevExpress.XtraEditors.Repository.RepositoryItemCheckEdit isTransItemCheckEdit;
        private DevExpress.XtraEditors.Repository.RepositoryItemCheckEdit isArchCheckEdit;
        private DevExpress.XtraGrid.Columns.GridColumn ApartmentColumn;
        private DevExpress.XtraGrid.Columns.GridColumn StreetColumn;
        private DevExpress.XtraGrid.Columns.GridColumn HouseColumn;
        private DevExpress.XtraGrid.Columns.GridColumn ResidentsNumberColumn;
        private DevExpress.XtraGrid.Columns.GridColumn FloorColumn;
    }
}

