//----------------------------------------------------------------------------------------
// patterns & practices - Smart Client Software Factory - Guidance Package
//
// This file was generated by the "Add Foundational Module" recipe.
//
// The LayoutView usercontrol defines a layout decoupled from the shell. 
// It provides a left and right workspace, menu bar, tool bar and status bar.
// These ui elements are added as extension sites.
//
// For more information see:
// ms-help://MS.VSCC.v80/MS.VSIPCC.v80/ms.scsf.2006jun/SCSF/html/03-290-Automation%20Add%20Foundational%20Module.htm
//
// Latest version of this Guidance Package: http://go.microsoft.com/fwlink/?LinkId=62182
//----------------------------------------------------------------------------------------

namespace Taumis.EnterpriseLibrary.Win.Modules.ReportModule
{
	partial class LayoutView {
		/// <summary> 
		/// Required designer variable.
		/// </summary>
		private System.ComponentModel.IContainer components = null;

		/// <summary> 
		/// Clean up any resources being used.
		/// </summary>
		/// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
		protected override void Dispose (bool disposing) {
			if (disposing && (components != null)) {
				components.Dispose ();
			}
			base.Dispose (disposing);
		}

		#region Component Designer generated code

		/// <summary> 
		/// Required method for Designer support - do not modify 
		/// the contents of this method with the code editor.
		/// </summary>
		private void InitializeComponent () {
            this._moduleWorkspace = new Microsoft.Practices.CompositeUI.WinForms.DeckWorkspace();
            this.reportViewSmartPartPlaceholder = new Microsoft.Practices.CompositeUI.WinForms.SmartPartPlaceholder();
            this.topViewSmartPartPlaceholder = new Microsoft.Practices.CompositeUI.WinForms.SmartPartPlaceholder();
            this.SuspendLayout();
            // 
            // _moduleWorkspace
            // 
            this._moduleWorkspace.Dock = System.Windows.Forms.DockStyle.Fill;
            this._moduleWorkspace.Location = new System.Drawing.Point(0, 0);
            this._moduleWorkspace.Name = "_moduleWorkspace";
            this._moduleWorkspace.Size = new System.Drawing.Size(613, 484);
            this._moduleWorkspace.TabIndex = 1;
            this._moduleWorkspace.Text = "_moduleWorkspace";
            // 
            // reportViewSmartPartPlaceholder
            // 
            this.reportViewSmartPartPlaceholder.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom)
                        | System.Windows.Forms.AnchorStyles.Left)
                        | System.Windows.Forms.AnchorStyles.Right)));
            this.reportViewSmartPartPlaceholder.BackColor = System.Drawing.Color.Transparent;
            this.reportViewSmartPartPlaceholder.Location = new System.Drawing.Point(0, 49);
            this.reportViewSmartPartPlaceholder.Margin = new System.Windows.Forms.Padding(0);
            this.reportViewSmartPartPlaceholder.Name = "reportViewSmartPartPlaceholder";
            this.reportViewSmartPartPlaceholder.Size = new System.Drawing.Size(613, 435);
            this.reportViewSmartPartPlaceholder.SmartPartName = "ReportView";
            this.reportViewSmartPartPlaceholder.TabIndex = 2;
            this.reportViewSmartPartPlaceholder.Text = "smartPartPlaceholder1";
            // 
            // topViewSmartPartPlaceholder
            // 
            this.topViewSmartPartPlaceholder.BackColor = System.Drawing.Color.Transparent;
            this.topViewSmartPartPlaceholder.Dock = System.Windows.Forms.DockStyle.Top;
            this.topViewSmartPartPlaceholder.Location = new System.Drawing.Point(0, 0);
            this.topViewSmartPartPlaceholder.Margin = new System.Windows.Forms.Padding(0);
            this.topViewSmartPartPlaceholder.Name = "topViewSmartPartPlaceholder";
            this.topViewSmartPartPlaceholder.Size = new System.Drawing.Size(613, 49);
            this.topViewSmartPartPlaceholder.SmartPartName = "TopView";
            this.topViewSmartPartPlaceholder.TabIndex = 3;
            // 
            // LayoutView
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Controls.Add(this.topViewSmartPartPlaceholder);
            this.Controls.Add(this.reportViewSmartPartPlaceholder);
            this.Controls.Add(this._moduleWorkspace);
            this.Name = "LayoutView";
            this.Size = new System.Drawing.Size(613, 484);
            this.ResumeLayout(false);

		}

		#endregion

		private Microsoft.Practices.CompositeUI.WinForms.DeckWorkspace _moduleWorkspace;
		private Microsoft.Practices.CompositeUI.WinForms.SmartPartPlaceholder reportViewSmartPartPlaceholder;
        private Microsoft.Practices.CompositeUI.WinForms.SmartPartPlaceholder topViewSmartPartPlaceholder;
	}
}
